version: "3.7"
services:
  maria_db:
    image: "mariadb:10.7.3"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: netzfilm
      MYSQL_USER: sa
      MYSQL_PASSWORD: geheim
      MYSQL_ROOT_PASSWORD: geheim