spring:
  #  spring-boot recently switched to a uuid-name for the db - so we set it hard
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE' # 'jdbc:h2:file:/data/demo;DB_CLOSE_ON_EXIT=FALSE'
    #  Auto configured by spring-boot
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:
  # enable h2-web-console
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#to be used for conditionals and tests
test:
  string: dev
