spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/netzfilm'
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password: geheim
  jpa:
    #  Not configured by spring-boot for other database
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #none, validate, update,
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
#to be used for conditionals and tests
test:
  string: prod
