spring:
  profiles:
    active: dev
  application:
    name: Netzfilm
  datasource:
    hikari:
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
      # in combination with jpa.properties.hibernate.connection.provider_disables_autocommit: true
      auto-commit: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        temp:
          # https://stackoverflow.com/questions/10075081/hibernate-slow-to-acquire-postgres-connection
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
  # ein paar configs für jackson, mit denen ich gute Erfahrung gemacht habe
  jackson:
    time-zone: UTC
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true

management:
  # enable more information on info
  info:
    env:
      enabled: true
    java:
      enabled: true
  # enable all actuators
  endpoints:
    web:
      exposure:
        include: "*"
  # enable more information on health
  endpoint:
    health:
      show-details: ALWAYS
      show-components: ALWAYS
